### ISSUE TITLE
I cannot access https://originui.com/

### ISSUE THREAD

**Issue by artiely** [origin-space/originui#117]
<img width="712" alt="image" src="https://github.com/user-attachments/assets/a284c35b-16a3-404e-b4bf-9792c709977f">
{"message":"API rate limit exceeded for 8.223.15.4. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

I cannot access https://originui.com/. I see an error and I'm not sure if it’s a problem on my end. How should I resolve this?

**Comment by pasqualevitiello** [comment]
Hey @artiely can you please check again?

**Comment by emigdio821** [comment]
I can confirm that is working now.

**Comment by pasqualevitiello** [comment]
Cool, thanks!
