### ISSUE TITLE
useImageUpload hook is not provided with upload file button component.

### ISSUE THREAD

**Issue by OsamaHIma** [origin-space/originui#156]
Hello wonderful team of **originUI**,  

First of all, thank you for your hard work and for sharing this amazing UI component library!  

### Issue  
In the **upload button** example provided in the documentation, the following code is included:  

```tsx
import { useImageUpload } from "@/hooks/use-image-upload";
```

However, it seems that the `useImageUpload` hook is not provided in the source code. This causes an error when trying to use the example component since the hook is missing.  

---

Thank you for looking into this! I really appreciate your help and am excited to use more of your components. 😊  

---

**Comment by pasqualevitiello** [comment]
Hey @OsamaHIma, thanks for your kind words. This is the file you must ensure to add to your app: https://github.com/origin-space/originui/blob/main/hooks/use-image-upload.ts

**Comment by OsamaHIma** [comment]
> Hey @OsamaHIma, thanks for your kind words. This is the file you must ensure to add to your app: https://github.com/origin-space/originui/blob/main/hooks/use-image-upload.ts
Ah, I see it now—my mistake! I just noticed the code is already available in the repo
Thanks again for the great work and support—you guys are awesome! 🚀
