### ISSUE TITLE
Accordion 08 and 10 variations do not show minus icon when expanded

### ISSUE THREAD

**Issue by pkgamma** [origin-space/originui#172]
I noticed that in the following two implementation of accordion components, the minus icon doesn't show in expanded state, but I'd assume it should switch from "+" to "-" like how [accordion-02](https://github.com/origin-space/originui/blob/1eb6ff98932c5b5563275ee61393683534006d7c/components/accordions/accordion-02.tsx) does it. Thank you for all your work on Origin UI @pasqualevitiello, I truly love all these beautifully implemented components! 

Places to be updated for your reference:

https://github.com/origin-space/originui/blob/1eb6ff98932c5b5563275ee61393683534006d7c/components/accordions/accordion-08.tsx#L47

https://github.com/origin-space/originui/blob/1eb6ff98932c5b5563275ee61393683534006d7c/components/accordions/accordion-10.tsx#L50

**Comment by pasqualevitiello** [comment]
fixed!
