### ISSUE TITLE
Small bug in titles of inputs in the docs

### ISSUE THREAD

**Issue by nahasco** [origin-space/originui#19]
<img width="742" alt="image" src="https://github.com/user-attachments/assets/bea38d33-f4bd-41ba-a823-bba8b1969b2b">

**Comment by naspnrd** [comment]
I can pick this issue, please assign it to me

**Comment by pasqualevitiello** [comment]
Hey @nahasco, could you please provide more details about the issue? I'm unable to identify the problem based on the screenshot attached. Thanks.

**Comment by nahasco** [comment]
> Hey @nahasco, could you please provide more details about the issue? I'm unable to identify the problem based on the screenshot attached. Thanks.

Shouldn't the titles be swapped?

**Comment by nahasco** [comment]
> Hey @nahasco, could you please provide more details about the issue? I'm unable to identify the problem based on the screenshot attached. Thanks.

Tested this again and it seems there was a misunderstanding on my side.
