### ISSUE TITLE
Traduzir input date picker

### ISSUE THREAD

**Issue by KaianDev** [origin-space/originui#2]
Bom dia

Como consigo usar e traduzir o input 42, date picker pra o padrão português brasileiro?

![image](https://github.com/user-attachments/assets/f7907d24-21d4-4e20-a2bc-4722df4b7a61)

**Comment by pasqualevitiello** [comment]
This component uses React Aria, please refer to the [documentation](https://react-spectrum.adobe.com/react-aria/internationalization.html).
