### ISSUE TITLE
Component name label proposal

### ISSUE THREAD

**Issue by baginski11** [origin-space/originui#21]
Here is a proposal of showing in the component's box a little label with the component name while the user hovers the box.

![image](https://github.com/user-attachments/assets/cd8cd6a2-39e6-444e-8bd1-c3bb494f65e8)

Its as simple as adding this code to the component's code:
```<p className='absolute text-muted-foreground/80 text-xs left-2 top-2 transition-all lg:opacity-0 lg:group-focus-within/item:opacity-100 lg:group-hover/item:opacity-100'>{componentName}</p>```

+ When I first discovered this project I really struggled to identify the individual components while I didn't want to have all of these inputs in my codebase.

**Comment by pasqualevitiello** [comment]
Hey @baginski11, thanks for the feedback! We’re currently focused on building more components, but we’ll definitely add those changes down the line. P.S. A trick to easily find the component in the project files is copying the component code and search in your editor ;)
