### ISSUE TITLE
Adding the gitthub button with arrow effect in the buttons list. (Feature Request) 

### ISSUE THREAD

**Issue by Gitstar-OC** [origin-space/originui#83]
Will my pr be approved if I add this button component which github uses for most of their websites ? 

Here's a link to it. 
https://mindect.vercel.app/learn

And here's a screenshot of it. 
![image](https://github.com/user-attachments/assets/485502b9-928b-4787-a8d5-67327cefec80)

Please check it out first!

**Comment by pasqualevitiello** [comment]
Cool idea, but we're keeping our UI pretty minimal – just aiming for functional over fancy. Thanks for asking!
