### ISSUE TITLE
Use shadcn@latest add <ORIGIN-UI-COMPONENT>?

### ISSUE THREAD

**Issue by bchatard** [origin-space/originui#84]
Hi !

Nice work on your components.

I have a dumb question: is it possible to add your component like we do with shadcn?

MagicUI propose this feature: https://magicui.design/docs/components/rainbow-button

Is it something you plan / want to implement?

Thanks,

**Comment by pasqualevitiello** [comment]
Hi, we have a [suggestions section](https://github.com/origin-space/originui/discussions/categories/suggestions) for this kind of requests. Right now, we're focusing our efforts on building components, but we plan to implement the new Shadcn CLI asap.
